---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/Users/bob0531/anaconda3/envs/myEnvironment/bin/python",
           required = T)
use_condaenv("m-team", required = T)
```

```{r}
library(reticulate)
conda_create("myEnvironment")
```

```{r}
library(reticulate)
conda_create("myEnvironment")

library(reticulate)
use_python("/Users/bob0531/anaconda3/envs/myEnvironment/bin/python", required = T)
use_condaenv("myEnvironment")
```

補充：
```{python}
listA=(10,2,3,6,8)
[listA[index] for index in range(len(listA)) if listA[index]>5]
```

###2.3 dictionary
```{python}
dictionaryA={
  "日期": [2001,2002,2003],
  "金額": [21000,33000,45880]}
dictionaryA

dictionaryA["數量"]=[100,200,300]
dictionaryA
```

```{python}
dictionaryA.keys()
```

```{python}
dictionaryA.values()
```

```{python}
dictionaryA.items()
```

```{python}
"日期" in dictionaryA
```

```{python}
dictionaryA.keys()
#dictionaryA.keys()[0] 錯誤

list(dictionaryA.keys())
list(dictionaryA.keys())[0]
```

```{python}
dictionaryA.items()
list(dictionaryA.items())
```

```{python}
list(dictionaryA) #只會顯示出keys
```

#課堂練習
```{python}
import pandas as pd

finStatement=pd.read_csv("http://mopsfin.twse.com.tw/opendata/t187ap06_O_ci.csv")
dict_finStatement=finStatement.to_dict()
```

tip:py$... 在python環境中可直接觀察資料
```{r}
py$finStatement
```
找出dict_finStatement中’營業利益（損失）‘為負的’公司名稱’
```{python}
dict_finStatement.keys()
```
1.找出損失的index
```{python}
profit=list(dict_finStatement.get("營業利益（損失）").values())

lossfirmkeys=[index for index in  range(len(profit)) if profit[index]<0]
```

2.由index進去公司找出名稱
```{python}
index=lossfirmkeys[100]
dict_finStatement.get("公司名稱")[index]   #或
dict_finStatement.get("公司名稱").get(index)

[dict_finStatement.get("公司名稱").get(index) for index in lossfirmkeys]

```

```{python}
{dict_finStatement.get('公司名稱').get(index): list(dict_finStatement.get( '營業利益（損失）').values())[index] for index in lossfirmkeys}

```





```{r}
# conda安裝方式
conda_install("m-team", # 沙盒環境名稱
              c("requests")) # 要安裝的modules
```

```{python}
import requests
response=requests.get("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3")
danceInfo=response.json()
```

```{python}
type(danceInfo)
```

```{python}
type(danceInfo[1])
```

```{python}
danceInfo[1].keys()
```

```{python}
danceInfo[1].values()
```

```{python}
danceInfo[1].get("showInfo")
```

```{python}
danceInfo[1].items()
```

###3.函數
```{python}
def test(input1, input2=0):
  print('input1 is ', input1)
  print('input2 is ', input2)
  return None
  
test(1,1) 
test(input1=1,input2=1)

test(1) # 動用到預設值
```

```{python}
def myfun(x,y):
  z=x+y #兩格空白或tab
  return z
  
myfun(5,6)

def myfun2(x,y):
  return x+y  #可省略
myfun2(5,6)

def myfun3(x,y=6):
  return x+y
myfun3(5,6)
myfun3(5)
myfun3(5,7)
```

```{python}
listL=(0,1,5)

a,b,c=listL #def ...(a,b,c)
a
b
c

a,*b=listL #def ...(a,*b)
a
b
```

```{python}
# (0.alpha=1,beta=3)

#def ...(a,**b)

b={"alpha":1,"beta":3}

```

```{python}
def test2(input1,*input3):
  print('input1 is ', input1)
  print('input3 is ', input3)
  return None
 
test2(1,1.2,4,5)
test2(1,[1.2,4],5)

test2(["1","b"],{2,5,7},10)
```

```{python}
def f(x, *seq, y):
    print("x is: ", x)
    print("seq is: ", seq)
    print("y is: ", y)
    return None

f(1, 2, 3, 4, 5)
f(1, 2, 3, 4, y=5)
```

```{python}
def test2(input1,**input4):
  print('input1 is ', input1)
  print('input4 is ', input4)
  return None
 
test3(1,a=10,b={2,3})
```

```{python}
def f(a,b,c):
   return a+b+c


f(1,3,4)
f(*[1,3],4)
f(1,*[3,4])
f(*[1,3,4])
```

```{python}
from math import *

def normal_pdf(z,mu,sigma):
  return 1/(sqrt(2*pi*sigma**2))*exp(-(z-mu)**2/(2*sigma**2))

normal_pdf(0.8,0,1)
```

```{python}
def utility_cobb_douglass(x,y,alpha=1,beta=3):
  
  utilValue = x**alpha*y**beta # 程序產生output值
  
  return utilValue # 傳回output值

utility_cobb_douglass(1,1,0.5,0.5)
utility_cobb_douglass(1,1)

```

---------------
```{python}
x,y,**parameters = (1,1,alpha=0.5,beta=0.5)
parameters{
alpha:3,
beta:1
}
```

```{python}
def utility_cobb_douglass(x,y,**parameters):
  alpha=parameters["alpha"]
  beta=parameters["beta"]
  utilValue = x**alpha*y**beta
  return utilValue
```

```{python}
global1=[1,3,[4,5]]
def funtest(x):
  x[0]="a" #定義式複製
  y=x[:]   #淺複製
  y[1]="b"
  y[2][1]="c"
  return None

global1
funtest(global1)
global1
```

```{python}
global1=[1,3,[4,5]]
funtest(global1.copy())
global1

import copy 
global1=[1,3,[4,5]]
funtest(copy.deepcopy(global1))
global1
```









