---
title: "課堂練習"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/Users/bob0531/anaconda3/envs/myEnvironment/bin/python",
           required = T)
use_condaenv("m-team", required = T)
```

```{python}
import numpy as np
```

```{python}
X_23=np.array([
  [-1,1,5], 
  [0,7,4 ]
])       

X_23.shape
```
計算有幾個軸線axis
```{python}
X_23.ndim
```

```{python}
x0=np.array([[2,3,5,7,9,11]])

x0
x0.shape
x0.shape=(2,3) # method直接改x0
x0
```

```{python}
x1=x0.copy()
x1.shape=(3,2)
x1
x0
```

```{python}
x1=x0.reshape((3,2)) # method不會改x0
x0
x1
```
# Array and flat array
```{python}
x1=np.array([[ 1., 2., 3.]])
x2=np.array([[1.],[2.],[3.]])

print(x1)
x1.shape 
print(x2)
x2.shape 
```
flat array
```{python}
x0=np.array([ 1., 0., 0.]) # 少了最外層[.]
print(x0)
x0.shape
x0.ndim 
```

```{python}
x1_flat=x1.flatten()
x1_flat
print(x1_flat)
x1_flat.shape
```
#Elementwise Operations
add:+
subtract: −
multiplication: ⊗
division: ⊘
 
```{python}
a = np.array(
  [[1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0]]
  )  

b = np.array(
  [[-1, 2.0, -2.0],
  [1.0,2.0,7.0]]
  )
a
b
```

```{python}
a+b
a-b
a*b # * 是elementwise product，不是矩陣相乘
a/b
```
#Broadcasting
```{python}
a = np.array([1.0, 2.0, 3.0]) 
a.shape=(1,3)

b = np.array(
  [[-1, 2.0, -2.0],
  [1.0,2.0,7.0]]
  ) # (2,3)
```

```{python}
a_broadcast=np.array(
  [
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0]
  ]
  )

a_broadcast.shape=(2,3)

print(a_broadcast)
```

```{python}
a+b == a_broadcast+b
a-b == a_broadcast-b
a*b == a_broadcast*b
a/b == a_broadcast/b
```

```{python}
x0=np.array([ 1., 0., 0.])
x1=np.array([[ 1., 2., 3.]])
x2=x1.reshape((3,1))
x0
x1
x2
x0+x1
x0+x2
```
#Vectorized function
```{python}
def addsubtract(a,b):
   if a > b:
       return a - b
   else:
       return a + b
```

```{python}
addsubtract([0,3,6,9],[1,3,5,7])
```

```{python}
vec_addsubtract = np.vectorize(addsubtract)
```

```{python}
vec_addsubtract([0,3,6,9],[1,3,5,7])
```

#Operations
```{python}
A=np.array(
  [
    [2, 4],
    [1, 3]
  ]
)

B=np.array(
  [
    [-1, 2],
    [-3, 4]
  ]
)

A*B # 不是矩陣相乘AB

A@B # 才是矩陣相乘```
```

```{python}
x1
x1.T
```
Only vector or matrix can be transposed, but not a flat array.
```{python}
x0=np.array([2,3,5])
print(x0)
print(x0.T) # no difference from x0
```
8.6.3 inverse & determinant
```{python}
from numpy.linalg import inv, det
```

```{python}
y=np.array([[2,3,4,6]]).T
x=np.array([
[1,1,1,1],
[0,-2,4,7]
]
).T

y
x
```
$$
\hat{\beta}=(x^Tx)^{-1}x^Ty
$$

```{python}
(inv(x.T@x))@x.T@y
```
#範例2
```{python}
x1=np.array([1,-1,1])
x1.shape=(3,1)
x2=np.array([4,7,3])
x2.shape=(3,1)
X=np.column_stack((x1,x2))
# x(xt x)^-1 xt
Px=X@inv(X.T@X)@X.T
Px
```

```{python}
y=np.array([2,-1,3])
y.shape=(3,1)
```

```{python}
y_hat=Px@y
```

```{python}
y_hat
y
e=y-y_hat
e
```

```{python}
y_hat.T@e
```

```{python}
(e.T@e)**(1/2)
```
## 範例
1.$f(z)$為常態分配pdf,自訂f函數(hint: `np.pi`,`np.exp()`)
```{python}
def normalPdf(z,mean=0,sigma=1):
    pdfvalue=np.exp(-((z-mean)/(sigma))**2/2)/((2*np.pi*sigma**2)**(0.5))
    return pdfvalue

normalPdf(1)
normalPdf(0)


```
2. vectorized normalPdf
```{python}
vec_normalPdf=np.vectorize(normalPdf)
vec_normalPdf(1)
```
3. 
$\epsilon_i=y_i-\hat{y}_i$
假設
$$
\epsilon_i\stackrel{iid}{~} N(0,1)
$$
令$\epsilon_i=y_i-\hat{y}_i$, 算每個$\epsilon_i$的pdf

```{python}
y=np.array([[2,3,4,6]]).T
x=np.array([
[1,1,1,1],
[0,-2,4,7]
]
).T
y
x
```

```{python}
yhat=x@inv(x.T@x)@x.T@y
e=y-yhat
```

```{python}
e_pdf=vec_normalPdf(e)
```
4. 取其$log$再相加

```{python}
np.log(e_pdf).sum()
```

```{python}
beta_hat=inv(x.T@x)@x.T@y
beta_hat
```





















